### ISSUE TITLE
add_nested_fields_link causes the page to reload

### ISSUE THREAD

**Issue by Sapherous** [ncri/nested_form_fields#68]
I'm having a weird issue where I have the following:

```
<%= f.nested_fields_for :empleados_incapacidades, wrapper_tag: "tr" do |i| %>
  <%= render "admin/empleados/empleados_incapacidades_fields", :f => i %>
<% end %>

<!-- And the link where I add  fields to the form -->
<div class="row-fluid text-left">
  <%= f.add_nested_fields_link :empleados_incapacidades, "Agregar Incapacidad", class: "btn btn-primary", id: "btn-agregar-deducciones"  %>
</div>
```

The issue appears when I navigate to the page where the form is rendered. When I click the add_nested_fields_link it reloads the page. For some reason, when I reload the page manually after it does it by itself, it works perfectly.

Also, when I it works, and I'm listening to the fields_added.nested_form_fields event

`$(document).unbind().on "fields_added.nested_form_fields", (event, param) ->`

it triggers the event twice. Is there a way to trigger the same events in a button, not a link?

Using:

Ruby 1.9.3-p551
Rails 4.1.0

**Comment by ncri** [comment]
It seems the nested form fields event handlers are not attached when you don't do a full page reload. You need to try to debug your javascript. Do you see any errors in the developer console (for example in Chrome)? 

I cannot tell what's wrong from here without a demo app showing the issue.

If you want an add fields button instead of a link, you can style the link like a button. I do that often in my projects.

**Comment by Sapherous** [comment]
You're absolutely right... 

The problem was here

`$(document).unbind().on "fields_added.nested_form_fields", (event, param) ->`

having the .unbind() method attached was causing the script to lose the event handlers. Removing that solved the problem.
